# Neural Network

In [32]:
# We will be using keras within tensorflow
import pandas as pd
import numpy as np
import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from tensorflow import keras 
from tensorflow.keras import layers

## Load and Review the data

In [33]:
# Load and partition the dataset
s_df = pd.read_csv('sonar.all-data.csv', header=None)

In [34]:
# Print the head of the dataframe
print(s_df.head())

       0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   

## Review the data

In [35]:
# Print the shape of the training data
print(s_df.shape)

# Print the length of the training labels
print(len(s_df.iloc[60]))

(208, 61)
61


In [36]:
# Print the first column of the 12th record
print(s_df[0][11])

0.0123


In [37]:
# Review the unique labels for the training data
unique_labels = s_df[60].unique()
print(unique_labels)

['R' 'M']


## Preprocess the data

### Encode the labels

In [38]:
# Initialize the LabelEncoder
label_encoder = LabelEncoder()
label_encoder.fit(s_df[60])

# Fit and transform the categorical labels into integer labels
encoded_labels = label_encoder.transform(s_df[60])

In [39]:
# Review the unique labels for the training data
print(encoded_labels)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [40]:
# Convert input to numpy array
np_s_df = np.array(s_df)
print(np_s_df)

[[0.02 0.0371 0.0428 ... 0.009 0.0032 'R']
 [0.0453 0.0523 0.0843 ... 0.0052 0.0044 'R']
 [0.0262 0.0582 0.1099 ... 0.0095 0.0078 'R']
 ...
 [0.0522 0.0437 0.018 ... 0.0077 0.0031 'M']
 [0.0303 0.0353 0.049 ... 0.0036 0.0048 'M']
 [0.026 0.0363 0.0136 ... 0.0061 0.0115 'M']]


In [41]:
# Assign variable X with all attributes
X = np.array(s_df.iloc[:, :4])

# Assign variable Y with the labels
y = np.array(s_df.iloc[:, 4])

In [42]:
print(X)
print(y)

[[0.02   0.0371 0.0428 0.0207]
 [0.0453 0.0523 0.0843 0.0689]
 [0.0262 0.0582 0.1099 0.1083]
 [0.01   0.0171 0.0623 0.0205]
 [0.0762 0.0666 0.0481 0.0394]
 [0.0286 0.0453 0.0277 0.0174]
 [0.0317 0.0956 0.1321 0.1408]
 [0.0519 0.0548 0.0842 0.0319]
 [0.0223 0.0375 0.0484 0.0475]
 [0.0164 0.0173 0.0347 0.007 ]
 [0.0039 0.0063 0.0152 0.0336]
 [0.0123 0.0309 0.0169 0.0313]
 [0.0079 0.0086 0.0055 0.025 ]
 [0.009  0.0062 0.0253 0.0489]
 [0.0124 0.0433 0.0604 0.0449]
 [0.0298 0.0615 0.065  0.0921]
 [0.0352 0.0116 0.0191 0.0469]
 [0.0192 0.0607 0.0378 0.0774]
 [0.027  0.0092 0.0145 0.0278]
 [0.0126 0.0149 0.0641 0.1732]
 [0.0473 0.0509 0.0819 0.1252]
 [0.0664 0.0575 0.0842 0.0372]
 [0.0099 0.0484 0.0299 0.0297]
 [0.0115 0.015  0.0136 0.0076]
 [0.0293 0.0644 0.039  0.0173]
 [0.0201 0.0026 0.0138 0.0062]
 [0.0151 0.032  0.0599 0.105 ]
 [0.0177 0.03   0.0288 0.0394]
 [0.01   0.0275 0.019  0.0371]
 [0.0189 0.0308 0.0197 0.0622]
 [0.024  0.0218 0.0324 0.0569]
 [0.0084 0.0153 0.0291 0.0432]
 [0.0195

In [43]:
# Split train and test data (test_size = 0.20, random_state=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [44]:
# Print the shape of X_train
print(X_train.shape)
# Print the shape of y_train
print(y_train.shape)

(166, 4)
(166,)


In [45]:
# Print the shape of X_test
print(X_test.shape)
# Print the shape of y_test
print(y_test.shape)

(42, 4)
(42,)


## Build the neural network

In [46]:
NB_CLASSES=1

# Build a 3 layer neural network (hint: review the LinkedIn Lerning Hands-on Lab Template)
model = keras.Sequential([
    layers.Dense(128, input_shape=(4,), activation='relu', name='Hidden-Layer-1'),
    layers.Dense(64, activation='relu', name='Hidden-Layer-2'),
    layers.Dense(NB_CLASSES, activation="softmax")
])

In [47]:
# Create the compilation step
model.compile(optimizer="adam",
              loss="binary_crossentropy", # binary_crossentropy is used for binary classification
              metrics=["accuracy"])

In [48]:
# Print the summary of the model
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Hidden-Layer-1 (Dense)      (None, 128)               640       
                                                                 
 Hidden-Layer-2 (Dense)      (None, 64)                8256      
                                                                 
 dense_1 (Dense)             (None, 1)                 65        
                                                                 
Total params: 8961 (35.00 KB)
Trainable params: 8961 (35.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [49]:
# Fit the data to the model (epochs=10, batch_size=42)
BATCH_SIZE = 42
EPOCHS = 10 

model.fit(X_train, y_train, batch_size=BATCH_SIZE, epochs=EPOCHS)

Epoch 1/10
4/4 [==============================] - 0s 842us/step - loss: 0.6878 - accuracy: 0.0000e+00
Epoch 2/10
4/4 [==============================] - 0s 669us/step - loss: 0.6645 - accuracy: 0.0000e+00
Epoch 3/10
4/4 [==============================] - 0s 642us/step - loss: 0.6399 - accuracy: 0.0000e+00
Epoch 4/10
4/4 [==============================] - 0s 616us/step - loss: 0.6110 - accuracy: 0.0000e+00
Epoch 5/10
4/4 [==============================] - 0s 609us/step - loss: 0.5770 - accuracy: 0.0000e+00
Epoch 6/10
4/4 [==============================] - 0s 598us/step - loss: 0.5386 - accuracy: 0.0000e+00
Epoch 7/10
4/4 [==============================] - 0s 909us/step - loss: 0.4967 - accuracy: 0.0000e+00
Epoch 8/10
4/4 [==============================] - 0s 716us/step - loss: 0.4538 - accuracy: 0.0000e+00
Epoch 9/10
4/4 [==============================] - 0s 655us/step - loss: 0.4112 - accuracy: 0.0000e+00
Epoch 10/10
4/4 [==============================] - 0s 825us/step - loss: 0.3721 - 

## Make Predictions

In [50]:
# Use model.predict to make predictions on the test data
predictions = model.predict(X_test)

2/2 [==============================] - 0s 1ms/step


In [51]:
# Print out the prediction of the first test record
print(predictions[0])

[1.]


In [52]:
# Print out the actual value of the first test record
first_test_record = X_test[0]
print("First test record: ", first_test_record)

First test record:  [0.0209 0.0191 0.0411 0.0321]


In [53]:
# Print out the prediction of the 11th test record
print(predictions[10])

[1.]


In [54]:
# Print out the actual value of the 11th test record
second_test_record = X_test[10]
print("Eleventh test record: ", second_test_record)

Eleventh test record:  [0.0762 0.0666 0.0481 0.0394]


## Evaluate the Model

In [55]:
# Print the test accuracy and loss of the model (hint: review the Hands-on Lab in Module 1
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"test_acc: {test_acc}")

2/2 [==============================] - 0s 2ms/step - loss: 0.3452 - accuracy: 0.0000e+00
test_acc: 0.0
